name: Copy the latest RFCs from the RFC Editor

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  rsync:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    # rsync -avz --delete --include="*.html" --exclude="*" rsync.rfc-editor.org::rfcs rfcs
    - uses: up9cloud/action-rsync@master
      env:
        HOST: rsync.rfc-editor.org
        MODE: pull
        ARGS: -avz --delete --include="*.html" --exclude="*"
        SOURCE: rfcs
        TARGET: ./rfcs

    # git add rfcs/*
    # git commit
    - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
      with:
        add: 'rfcs'
        author_name: RFC Editor Bot
        author_email: rlb+rfced@ipv.sx
        message: 'Update with latest rsync'
