name: Copy the latest RFCs from the RFC Editor

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  rsync:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: install rsync
      run: |
        brew install rsync

    - name: run rsync
      run: |
        rsync -avzP --delete --include="*.html" --exclude="*" rsync.rfc-editor.org::rfcs rfcs

    - name: add and commit
      uses: EndBug/add-and-commit@v9
      with:
        add: 'rfcs'
        author_name: RFC Editor Bot
        author_email: rlb+rfced@ipv.sx
        message: 'Update with latest rsync'
